ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += periph_rtc_series$(EFM32_SERIES)
endif

ifneq (,$(filter periph_rtt,$(USEMODULE)))
  USEMODULE += periph_rtt_series$(EFM32_SERIES)
endif

ifneq (,$(filter efm32_coretemp,$(USEMODULE)))
  FEATURES_REQUIRED += periph_adc
endif