# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup JLink for flashing
export JLINK_DEVICE := $(CPU_MODEL)
export JLINK_PRE_FLASH = r
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk