include ../Makefile.drivers_common

# Enable at least one of the modules for the test application to function.
#USEMODULE += tda7439
USEMODULE += tda7440
#USEMODULE += tda7449

USEMODULE += shell

include $(RIOTBASE)/Makefile.include
